spring.application.name=liberty-api

# Datasource
spring.datasource.url=${dbUrl}
spring.datasource.username=${dbUser}
spring.datasource.password=${dbPassword}

# Hibernatespring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.enabled=false

